version: '3.9'

services:
  wordpress:
    image: arm64v8/wordpress:latest
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    networks:
      - ozel-ag

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - ozel-ag

networks:
  ozel-ag:
    external: true
